window.projectData = [
  { id:1, image:'assets/images/portfolio/logo/project-1.webp', en:{title:'Velloré Paris',category:'Logo Design',description:'A refined fashion identity balancing timeless editorial character with a distinctive gold-foil monogram.',client:'Velloré Paris',services:'Logo strategy, monogram design, art direction'}, zh:{title:'维洛蕾巴黎',category:'标志设计',description:'以经典编辑气质与独特烫金字母标志相结合，打造精致的时尚品牌形象。',client:'维洛蕾巴黎',services:'标志策略、字母标志设计、艺术指导'} },
  { id:2, image:'assets/images/portfolio/branding/project-1.webp', en:{title:'Élan Brand System',category:'Brand Identity',description:'A complete identity system designed to feel confident, coherent and premium across every brand touchpoint.',client:'Élan Collective',services:'Brand strategy, visual identity, guidelines'}, zh:{title:'伊兰品牌系统',category:'品牌形象',description:'打造自信、统一且高级的完整视觉系统，覆盖每一个品牌接触点。',client:'伊兰品牌集团',services:'品牌策略、视觉形象、品牌规范'} },
  { id:3, image:'assets/images/portfolio/social/project-1.webp', en:{title:'Aurelia Social',category:'Social Media Design',description:'A flexible social campaign system created for an elevated cosmetic launch across feeds, stories and paid media.',client:'Aurelia Beauty',services:'Campaign concept, social templates, art direction'}, zh:{title:'奥蕾莉亚社交活动',category:'社交媒体设计',description:'为高端美妆新品发布打造灵活统一的社交活动系统，覆盖动态、限时内容与付费媒体。',client:'奥蕾莉亚美妆',services:'活动概念、社交模板、艺术指导'} },
  { id:4, image:'assets/images/portfolio/poster/project-1.webp', en:{title:'Midnight Sessions',category:'Poster Design',description:'An atmospheric concert campaign using expressive typography and cinematic contrast to command attention outdoors.',client:'Midnight Sessions',services:'Campaign design, poster system, outdoor adaptation'}, zh:{title:'午夜现场',category:'海报设计',description:'运用富有表现力的字体与电影感对比，打造在户外环境中引人注目的音乐会宣传活动。',client:'午夜现场',services:'活动设计、海报系统、户外延展'} },
  { id:5, image:'assets/images/portfolio/flyer/project-1.webp', en:{title:'Noir Dining',category:'Flyer Design',description:'An elegant restaurant promotion pairing restrained typography with tactile print details and clear hierarchy.',client:'Noir Dining',services:'Flyer design, print preparation, art direction'}, zh:{title:'诺瓦餐饮',category:'宣传单设计',description:'以克制字体、细腻印刷质感与清晰信息层级，呈现优雅的餐厅推广设计。',client:'诺瓦餐饮',services:'宣传单设计、印刷制作、艺术指导'} },
  { id:6, image:'assets/images/portfolio/banner/project-1.webp', en:{title:'Atelier Digital',category:'Banner Design',description:'A premium digital banner system built for clarity, flexible messaging and consistent campaign recognition.',client:'Atelier Digital',services:'Digital campaign, banner system, responsive adaptation'}, zh:{title:'雅特数字',category:'横幅设计',description:'兼顾清晰表达、灵活信息与统一活动识别度的高级数字横幅系统。',client:'雅特数字',services:'数字活动、横幅系统、响应式延展'} },
  { id:7, image:'assets/images/portfolio/business-card/project-1.webp', en:{title:'Obsidian Cards',category:'Business Card Design',description:'A tactile black-and-gold stationery concept combining foil, letterpress and restrained luxury.',client:'Obsidian Advisory',services:'Business card design, material selection, production artwork'}, zh:{title:'黑曜名片',category:'名片设计',description:'结合烫金、凸版印刷与克制奢华风格的黑金触感文具方案。',client:'黑曜顾问',services:'名片设计、材质选择、生产文件'} },
  { id:8, image:'assets/images/portfolio/menu/project-1.webp', en:{title:'Maison Café',category:'Menu Design',description:'A warm, refined café menu designed to improve navigation while strengthening the hospitality experience.',client:'Maison Café',services:'Menu structure, editorial design, print production'}, zh:{title:'美颂咖啡馆',category:'菜单设计',description:'温暖精致的咖啡馆菜单，在提升浏览效率的同时强化餐饮体验。',client:'美颂咖啡馆',services:'菜单结构、编辑设计、印刷制作'} },
  { id:9, image:'assets/images/portfolio/packaging/project-1.webp', en:{title:'Aurea Coffee',category:'Packaging Design',description:'A premium coffee packaging family combining strong shelf presence with understated gold detailing.',client:'Aurea Coffee',services:'Packaging concept, label system, production artwork'}, zh:{title:'奥瑞亚咖啡',category:'包装设计',description:'以醒目的货架表现与克制烫金细节打造高级咖啡包装系列。',client:'奥瑞亚咖啡',services:'包装概念、标签系统、生产文件'} },
  { id:10, image:'assets/images/portfolio/logo/project-2.webp', en:{title:'Nexora Technologies',category:'Logo Design',description:'A precise technology mark designed to communicate momentum, intelligence and dependable performance.',client:'Nexora Technologies',services:'Logo strategy, symbol design, signage direction'}, zh:{title:'奈索拉科技',category:'标志设计',description:'以精准造型传达发展动力、智慧与可靠性能的科技品牌标志。',client:'奈索拉科技',services:'标志策略、图形设计、标牌指导'} },
  { id:11, image:'assets/images/portfolio/branding/project-4.webp', en:{title:'Maison Stationery',category:'Brand Identity',description:'A sophisticated stationery suite translating a luxury identity into practical, beautifully crafted applications.',client:'Maison & Co.',services:'Stationery system, print direction, brand application'}, zh:{title:'美颂文具系统',category:'品牌形象',description:'将奢华品牌形象转化为实用且工艺精致的完整文具应用系统。',client:'美颂公司',services:'文具系统、印刷指导、品牌应用'} },
  { id:12, image:'assets/images/portfolio/packaging/project-2.webp', en:{title:'Lumière Parfum',category:'Packaging Design',description:'An elegant fragrance presentation built around sculptural glass, embossing and luminous metallic accents.',client:'Lumière Parfum',services:'Packaging design, structural direction, finishing specification'}, zh:{title:'露米埃香氛',category:'包装设计',description:'围绕雕塑感玻璃、压纹与明亮金属细节打造优雅香氛包装。',client:'露米埃香氛',services:'包装设计、结构指导、工艺规范'} },
  { id:13, image:'assets/images/portfolio/website/project-1.webp', en:{title:'Creative Agency Website',category:'Website Design',description:'A focused agency website concept balancing bold portfolio presentation with a clear path to enquiry.',client:'Independent Creative Agency',services:'UX direction, interface design, responsive system'}, zh:{title:'创意机构网站',category:'网站设计',description:'兼顾大胆作品展示与清晰咨询路径的创意机构网站概念。',client:'独立创意机构',services:'用户体验指导、界面设计、响应式系统'} },
  { id:14, image:'assets/images/portfolio/website/project-2.webp', en:{title:'Personal Portfolio',category:'Website Design',description:'A minimal portfolio experience designed to place the work first across desktop and mobile devices.',client:'Independent Designer',services:'Content structure, interface design, mobile adaptation'}, zh:{title:'个人作品集',category:'网站设计',description:'以作品为核心，为桌面与移动设备打造极简作品集体验。',client:'独立设计师',services:'内容结构、界面设计、移动适配'} },
  { id:15, image:'assets/images/portfolio/website/project-3.webp', en:{title:'Restaurant Website',category:'Website Design',description:'A refined hospitality interface connecting atmosphere, menu discovery and effortless reservations.',client:'Independent Restaurant',services:'UX planning, interface design, responsive layout'}, zh:{title:'餐厅网站',category:'网站设计',description:'将空间氛围、菜单浏览与便捷预订融为一体的精致餐饮界面。',client:'独立餐厅',services:'用户体验规划、界面设计、响应式布局'} },
  { id:16, image:'assets/images/portfolio/website/project-4.webp', en:{title:'Business Landing Page',category:'Website Design',description:'A conversion-focused landing page combining clear messaging, premium presentation and responsive performance.',client:'Growth-Focused Business',services:'Page strategy, interface design, basic SEO setup'}, zh:{title:'企业落地页',category:'网站设计',description:'兼顾清晰信息、高级呈现与响应式性能的转化型企业落地页。',client:'成长型企业',services:'页面策略、界面设计、基础搜索优化'} }
];
