window.socialLinks = [
  { key: 'instagram', label: 'Instagram', zhLabel: '照片墙', url: 'https://instagram.com/yourusername', icon: '<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" class="fill"/></svg>' },
  { key: 'behance', label: 'Behance', zhLabel: '作品平台', url: 'https://behance.net/yourusername', icon: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 5h7c3 0 4.5 1.5 4.5 3.7 0 1.5-.7 2.6-2 3.2 2 .5 3 1.8 3 3.7 0 2.7-2 4.4-5.3 4.4H3V5Zm4 3v2.7h2.5c1 0 1.6-.5 1.6-1.4S10.5 8 9.5 8H7Zm0 5.6V17h2.9c1.3 0 2-.6 2-1.7s-.7-1.7-2-1.7H7Z"/><path d="M16 7h5M15.5 15.3c.2 1.5 1 2.3 2.3 2.3 1 0 1.7-.4 2.1-1.1h3.5c-.8 2.5-2.7 3.8-5.7 3.8-3.7 0-6-2.3-6-5.9 0-3.5 2.4-5.9 5.9-5.9 4 0 6.1 2.7 5.8 6.8h-7.9Zm4.4-2.2c-.2-1.3-1-2-2.2-2-1.2 0-1.9.7-2.2 2h4.4Z" transform="scale(.72) translate(10 6)"/></svg>' },
  { key: 'linkedin', label: 'LinkedIn', zhLabel: '领英', url: 'https://linkedin.com/in/yourusername', icon: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 8.5V21M5 3.5v.1M10 21V8.5m0 5.3c0-3 1.5-5.3 4.7-5.3 3.1 0 4.3 2 4.3 5V21"/></svg>' },
  { key: 'facebook', label: 'Facebook', zhLabel: '脸书', url: 'https://facebook.com/yourusername', icon: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 21v-8h3l.5-3H14V8c0-1 .4-2 2-2h2V3.2c-.6-.1-1.7-.2-2.8-.2C12.4 3 10 4.7 10 8v2H7v3h3v8"/></svg>' },
  { key: 'xiaohongshu', label: 'Xiaohongshu', zhLabel: '小红书', url: 'https://www.xiaohongshu.com/user/profile/youruserid', icon: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5h16v14H4zM8 9v6m4-6v6m4-6v6M6 12h12"/></svg>' }
];

window.siteTranslations = {
  zh: {
    'Home':'首页','About':'关于我们','Services':'服务','Work':'作品','Start a project':'开始项目',
    'Strategy-led. Detail-obsessed.':'策略驱动，专注细节。','We create brands':'我们打造品牌','with':'创造','lasting':'长久','impact.':'影响力。',
    'INfinity is an independent design studio crafting distinctive identities, websites, packaging and campaigns for businesses ready to stand apart.':'INfinity 是一家独立设计工作室，为希望脱颖而出的企业打造独特的品牌形象、网站、包装与营销活动。',
    'View selected work':'查看精选作品','Work with us':'与我们合作','Scroll to explore':'滚动探索',
    'BRAND SYSTEM / 01':'品牌系统 / 01','FORM':'形式','FOLLOWS':'源于','FEELING.':'感受。','DESIGN WITH INTENT':'用心设计','Award-minded craft':'获奖级工艺','PREMIUM GRAPHIC DESIGN':'高端平面设计','DESIGN STUDIO':'设计工作室',
    'About the studio':'关于工作室','Design that feels':'设计自然','inevitable.':'而然。',
    'We believe exceptional design is not decoration. It is clarity, character and commercial advantage—expressed beautifully.':'我们相信，卓越设计并非装饰，而是以美学方式呈现清晰度、个性与商业优势。',
    'INfinity Design Studio partners with founders and forward-thinking businesses to build visual worlds that are coherent, memorable and made to endure.':'INfinity Design Studio 与创始人及前瞻型企业合作，构建统一、难忘且经久不衰的视觉世界。',
    'Projects crafted':'完成项目','Years of practice':'设计经验','Client referrals':'客户推荐',
    'Creative capabilities':'创意服务','Built for every':'为每一个','brand moment.':'品牌时刻而设计。',
    'From the first mark to the final campaign, every touchpoint is designed as one considered system.':'从第一个标志到最终营销活动，每个触点都被精心设计为统一系统。',
    'Logo Design':'标志设计','Brand Identity':'品牌形象','Social Media Design':'社交媒体设计','Poster Design':'海报设计','Flyer Design':'宣传单设计','Banner Design':'横幅设计','Business Card Design':'名片设计','Menu Design':'菜单设计','Packaging Design':'包装设计','Website Design':'网站设计',
    'Distinctive marks designed for recognition and longevity.':'打造易于识别且经久耐用的独特标志。','Complete visual systems with strategy, voice and guidelines.':'以策略、品牌语言和规范构建完整视觉系统。','Cohesive content that earns attention and builds affinity.':'通过统一内容吸引关注并建立品牌认同。','Bold compositions that communicate in an instant.':'以醒目构图快速传递核心信息。','Clear, compelling print collateral made to convert.':'清晰有力的印刷物料，助力业务转化。','High-impact visuals for digital and physical spaces.':'为数字和实体空间打造高影响力视觉。','Premium stationery that makes every introduction count.':'用高级文具设计让每次介绍更具价值。','Beautiful, intuitive menus shaped around the experience.':'围绕体验打造美观且直观的菜单。','Shelf-ready packaging with presence and purpose.':'兼具视觉吸引力与商业目标的成品包装。','Responsive, mobile-friendly websites with considered UI and basic SEO foundations.':'打造响应式、移动友好的网站，兼顾界面设计与基础 SEO。','View examples':'查看案例',
    'Selected Work':'精选作品','Ideas, made':'将创意化为','tangible.':'真实成果。','A collection of branding, digital, print, and packaging projects created to help businesses stand out.':'精选品牌、数字、印刷与包装项目，帮助企业脱颖而出。','All':'全部','Logo':'标志','Branding':'品牌','Website':'网站','Social Media':'社交媒体','Poster':'海报','Flyer':'宣传单','Banner':'横幅','Business Card':'名片','Menu':'菜单','Packaging':'包装','View Project →':'查看项目 →',
    'Velloré Paris':'维洛蕾巴黎','Élan Brand System':'伊兰品牌系统','Aurelia Social':'奥蕾莉亚社交活动','Midnight Sessions':'午夜现场','Noir Dining':'诺瓦餐饮','Atelier Digital':'雅特数字','Obsidian Cards':'黑曜名片','Maison Café':'美颂咖啡馆','Aurea Coffee':'奥瑞亚咖啡','Nexora Technologies':'奈索拉科技','Maison Stationery':'美颂文具系统','Lumière Parfum':'露米埃香氛','Creative Agency Website':'创意机构网站','Personal Portfolio':'个人作品集','Restaurant Website':'餐厅网站','Business Landing Page':'企业落地页',
    '01 / LOGO':'01 / 标志','02 / BRANDING':'02 / 品牌','03 / SOCIAL MEDIA':'03 / 社交媒体','04 / POSTER':'04 / 海报','05 / FLYER':'05 / 宣传单','06 / BANNER':'06 / 横幅','07 / BUSINESS CARD':'07 / 名片','08 / MENU':'08 / 菜单','09 / PACKAGING':'09 / 包装','10 / LOGO':'10 / 标志','11 / BRANDING':'11 / 品牌','12 / PACKAGING':'12 / 包装','13 / WEBSITE':'13 / 网站','14 / WEBSITE':'14 / 网站','15 / WEBSITE':'15 / 网站','16 / WEBSITE':'16 / 网站',
    'Design Process':'设计流程','A clear path to':'通往卓越作品的','exceptional work.':'清晰路径。','Our focused process keeps every project collaborative, considered and moving forward.':'我们专注的流程确保每个项目协作顺畅、思考周全并持续推进。','Discovery':'探索','Concept':'概念','Design':'设计','Refinement':'优化','Delivery':'交付','We learn your goals, audience and competitive landscape.':'了解您的目标、受众和竞争环境。','We define the creative direction and strategic idea.':'明确创意方向与策略理念。','We translate the direction into a distinctive visual system.':'将方向转化为独特的视觉系统。','We sharpen every detail through focused collaboration.':'通过专注协作打磨每个细节。','You receive organized, high-resolution, commercial-ready files.':'交付整理完善、高分辨率且可商用的文件。',
    'Why choose INfinity':'为何选择 INfinity','Small studio.':'小型工作室。','Serious impact.':'创造深远影响。','Direct collaboration, senior-level thinking and craft that never gets delegated down the line.':'直接协作、资深思维与始终如一的精湛工艺。','Original custom design':'原创定制设计','Professional communication':'专业沟通','Fast turnaround':'快速交付','Multiple revisions':'多轮修改','High-resolution files':'高分辨率文件','Commercial-ready output':'可商用成果',
    'Client words':'客户评价','Frequently asked':'常见问题','Questions,':'问题，','answered.':'为您解答。','Need something else? Send us a note and we’ll be happy to help.':'还有其他问题？欢迎联系我们，我们很乐意提供帮助。','What does a typical project include?':'一个常规项目包含哪些内容？','How long does a branding project take?':'品牌项目通常需要多长时间？','Do you work with international clients?':'你们是否与国际客户合作？','What do you need to get started?':'开始项目需要准备什么？',
    'Start a conversation':'开始沟通','Let’s create':'让我们共同创造','something':'一些','iconic.':'标志性的作品。','Tell us about your idea, goals and timeline. We’ll respond within two business days.':'请告诉我们您的想法、目标和时间安排。我们将在两个工作日内回复。','Email us ↗':'发送邮件 ↗','WhatsApp ↗':'WhatsApp ↗','Your name':'您的姓名','Email address':'电子邮箱','Business name':'企业名称','Service needed':'所需服务','Choose a service':'选择服务','Budget range':'预算范围','Choose a range':'选择范围','Under $500':'低于 $500','Project details':'项目详情','Send inquiry':'提交咨询',
    'Client Reviews':'客户评价','INfinity exceeded our expectations. The design and attention to detail were outstanding.':'INfinity 超出了我们的预期，设计品质与细节处理都非常出色。','Founder, TechNova':'TechNova 创办人','Professional, creative, and reliable. Our brand has never looked better.':'专业、有创意且值得信赖。我们的品牌形象从未如此出色。','Marketing Director, Bloom Co.':'Bloom Co. 市场总监','A truly collaborative experience with results that speak for themselves.':'整个合作过程非常顺畅，最终成果足以说明一切。','CEO, Elevate Studio':'Elevate Studio 首席执行官',
    'Privacy Policy':'隐私政策','Terms of Service':'服务条款','© 2026 INfinity Design Studio. All rights reserved.':'© 2026 INfinity Design Studio。保留所有权利。','INfinity / SERVICE EXAMPLES':'INfinity / 服务案例','Service examples':'服务案例',
    'logo':'标志','branding':'品牌','website':'网站','social':'社交媒体','poster':'海报','flyer':'宣传单','banner':'横幅','business card':'名片','menu':'菜单','packaging':'包装',
    'Trusted by people':'深受勇于创新者','building boldly.':'的信赖。','Thoughtful partnerships and design outcomes that help ambitious businesses move forward.':'以用心合作与优秀设计成果，助力有抱负的企业持续前进。',
    'INfinity didn’t just redesign our identity—they gave our business a new level of confidence. Every detail feels intentional, premium and unmistakably ours.':'INfinity 不仅重新设计了我们的品牌形象，更为企业带来了全新的自信。每个细节都精心考量、高级且独具特色。',"INfinity didn't just redesign our identity—they gave our business a new level of confidence. Every detail feels intentional, premium and unmistakably ours.":'INfinity 不仅重新设计了我们的品牌形象，更为企业带来了全新的自信。每个细节都精心考量、高级且独具特色。','Amelia Reed':'阿米莉亚·里德','Founder, Maison & Co.':'美颂公司创办人',
    'The process was clear, collaborative and genuinely strategic. Our new visual system finally reflects the quality of the business behind it.':'整个流程清晰、协作顺畅且真正具有策略性。新的视觉系统终于体现了我们企业的品质。','Daniel Koh':'丹尼尔·许','Director, Vertex Systems':'维泰系统总监',
    'From packaging to digital launch assets, everything felt connected. The result was polished, distinctive and ready for real commercial use.':'从包装到数字发布素材，一切都紧密相连。最终成果精致、独特，并可直接投入商业使用。','Sara Malik':'萨拉·马利克','Founder, Aurelia':'奥蕾莉亚创办人',
    'Every engagement is tailored, but typically includes discovery, creative direction, concept development, refinement and production-ready final assets.':'每个项目都会量身定制，通常包括探索、创意方向、概念开发、优化以及可直接使用的最终文件。','Most identity projects take four to eight weeks, depending on scope, feedback cadence and the number of required applications.':'大多数品牌项目需要四到八周，具体取决于项目范围、反馈节奏和所需应用数量。','Yes. Our process is designed for seamless remote collaboration with businesses anywhere in the world.':'是的，我们的流程专为顺畅的远程协作而设计，可服务全球企业。','A clear brief, your goals and an initial conversation are enough. We will guide you through everything else.':'一份清晰的需求、您的目标和一次初步沟通就足够了，其余部分我们会全程引导。',
    'No templates or borrowed trends—only original work shaped around your story.':'拒绝模板和跟风，只为您的故事打造原创作品。','A clear, collaborative process with thoughtful updates at every stage.':'清晰协作的流程，并在每个阶段提供周到更新。','Focused project schedules keep momentum high without compromising craft.':'专注的项目安排，在不牺牲品质的前提下保持高效推进。','Structured refinement rounds make sure every detail feels right.':'结构化的优化轮次，确保每个细节都恰到好处。','Organized final assets for print, web, social and every application.':'为印刷、网站、社交媒体及各类应用提供整理完善的最终文件。','Flexible systems created to perform consistently in the real world.':'打造灵活系统，在真实商业环境中保持一致表现。',
    'Luxury Fashion Logo · Gold Foil':'奢侈时尚标志 · 烫金','Identity · Guidelines · Stationery':'品牌形象 · 规范 · 文具','Instagram · Cosmetic Campaign':'社交平台 · 美妆活动','Concert Poster · Billboard':'音乐会海报 · 广告牌','Restaurant Flyer · Print':'餐厅宣传单 · 印刷','Website Hero Banner':'网站主视觉横幅','Black · Gold Foil · Letterpress':'黑色 · 烫金 · 凸版印刷','Café Menu · Hospitality':'咖啡馆菜单 · 餐饮','Coffee Packaging · Gold Foil':'咖啡包装 · 烫金','Technology Logo · Metal Signage':'科技标志 · 金属标牌','Letterhead · Envelope · Notebook':'信纸 · 信封 · 笔记本','Perfume Box · Glass · Foil':'香水盒 · 玻璃 · 烫金','Website UI · Responsive Design':'网站界面 · 响应式设计','Portfolio UI · Mobile-Friendly':'作品集界面 · 移动友好','Hospitality UI · Responsive Layout':'餐饮界面 · 响应式布局','Landing Page · Basic SEO Setup':'落地页 · 基础搜索优化',
    'Please enter a valid email address.':'请输入有效的电子邮箱。','Please complete all required fields.':'请填写所有必填字段。','Your details are ready. Connect Formspree or EmailJS to send this form.':'资料已准备完成。连接 Formspree 或 EmailJS 后即可发送表单。'
  },
  placeholders: { zh: { 'Jane Smith':'您的姓名','jane@company.com':'您的邮箱','Your business or brand':'您的企业或品牌','Your vision, goals and preferred timeline...':'请描述您的愿景、目标与期望时间…' } }
};
